# Generated by Django 4.1.3 on 2022-11-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('photo', models.ImageField(upload_to='uploads/', verbose_name='photo')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('seccond_name', models.CharField(max_length=100, verbose_name='seccond_name')),
                ('third_name', models.CharField(max_length=100, verbose_name='third_name')),
                ('number', models.CharField(max_length=100, verbose_name='number')),
            ],
        ),
    ]
